"use client";
import { Bot, Brain, Loader2, Shield, ShieldAlert } from "lucide-react";
import type { AIAnalysis, AIKeyConfig } from "@/types";
function MitreBadge({technique,tactic}:{technique:string;tactic:string}){return <div className="flex items-center gap-2 flex-wrap"><span className="text-xs font-mono font-bold text-cyan-300 bg-cyan-900/30 border border-cyan-800/50 px-2 py-0.5 rounded">{technique}</span><span className="text-xs text-slate-400">{tactic}</span></div>;}
function ActionBadge({action}:{action:string}){const style={IP_BLOCKED:"bg-rose-500/10 border-rose-500/30 text-rose-300",SESSION_KILLED:"bg-orange-500/10 border-orange-500/30 text-orange-300",PROCESS_TERMINATED:"bg-purple-500/10 border-purple-500/30 text-purple-300"}[action]??"bg-slate-700 border-slate-600 text-slate-300";const label={IP_BLOCKED:"🔒 IP Blocked",SESSION_KILLED:"⚡ Session Killed",PROCESS_TERMINATED:"🛑 Process Terminated"}[action]??action;return <span className={`text-xs font-semibold px-2.5 py-1 rounded-lg border ${style}`}>{label}</span>;}
function RiskGauge({score}:{score:number}){const color=score>=90?"text-rose-400":score>=70?"text-amber-400":"text-emerald-400";const barColor=score>=90?"bg-rose-500":score>=70?"bg-amber-500":"bg-emerald-500";return <div className="space-y-1.5"><div className="flex items-center justify-between"><span className="text-[10px] text-slate-500 uppercase tracking-wider">Risk Score</span><span className={`text-lg font-black font-mono ${color}`}>{score}<span className="text-xs font-normal text-slate-500">/100</span></span></div><div className="h-1.5 rounded-full bg-slate-800 overflow-hidden"><div className={`h-full rounded-full transition-all duration-700 ${barColor}`} style={{width:`${score}%`}}/></div></div>;}
interface CopilotPanelProps{analysis:AIAnalysis|null;isAnalyzing:boolean;aiConfig:AIKeyConfig|null;onOpenKeyModal:()=>void;}
export default function CopilotPanel({analysis,isAnalyzing,aiConfig,onOpenKeyModal}:CopilotPanelProps){
  return(
    <div className="flex flex-col h-full">
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-slate-700/60 shrink-0"><Bot className="w-4 h-4 text-cyan-400"/><span className="text-xs font-semibold text-slate-300 uppercase tracking-widest">AI Copilot</span>{aiConfig?<button onClick={onOpenKeyModal} className="ml-auto text-[10px] text-slate-500 hover:text-slate-300 border border-slate-700 hover:border-slate-500 px-2 py-0.5 rounded-md">{aiConfig.provider} · {aiConfig.key.slice(0,6)}…</button>:<button onClick={onOpenKeyModal} className="ml-auto text-[10px] text-cyan-400 hover:text-cyan-300 border border-cyan-700/40 hover:border-cyan-500/60 px-2 py-0.5 rounded-md">+ Add API Key</button>}</div>
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {!aiConfig&&<div className="flex flex-col items-center justify-center h-full gap-3 text-center px-4"><div className="w-12 h-12 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center"><Brain className="w-6 h-6 text-cyan-400"/></div><p className="text-sm font-medium text-slate-300">Connect the AI Copilot</p><p className="text-xs text-slate-500 leading-relaxed max-w-xs">Add a Groq, OpenAI, or DeepSeek API key to enable AI-powered threat analysis.</p><button onClick={onOpenKeyModal} className="mt-2 px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-sm font-medium transition-colors">Configure API key</button></div>}
        {aiConfig&&isAnalyzing&&<div className="flex flex-col items-center justify-center h-full gap-3"><Loader2 className="w-8 h-8 text-cyan-400 animate-spin"/><p className="text-xs text-slate-400">Analysing threat telemetry…</p></div>}
        {aiConfig&&!isAnalyzing&&!analysis&&<div className="flex flex-col items-center justify-center h-full gap-2 text-slate-600"><ShieldAlert className="w-8 h-8 opacity-30"/><p className="text-xs">Run a simulation to trigger AI analysis.</p></div>}
        {analysis&&!isAnalyzing&&<div className="space-y-4"><div className="p-3 rounded-xl bg-slate-800/50 border border-slate-700/60"><RiskGauge score={analysis.risk_score}/></div><div className="space-y-1.5"><p className="text-[10px] text-slate-500 uppercase tracking-wider font-medium">MITRE ATT&CK</p><MitreBadge technique={analysis.mitre_technique} tactic={analysis.mitre_tactic}/></div><div className="space-y-1.5"><p className="text-[10px] text-slate-500 uppercase tracking-wider font-medium">Analyst Summary</p><div className="p-3 rounded-xl bg-slate-800/40 border border-slate-700/50"><p className="text-xs text-slate-300 leading-relaxed">{analysis.summary}</p></div></div><div className="space-y-2"><p className="text-[10px] text-slate-500 uppercase tracking-wider font-medium">Automated Response</p><ActionBadge action={analysis.action_taken}/><div className="flex items-start gap-2 p-3 rounded-xl bg-emerald-900/15 border border-emerald-700/30"><Shield className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5"/><p className="text-xs text-emerald-200/80 leading-relaxed">{analysis.action_detail}</p></div></div></div>}
      </div>
    </div>
  );
}
