import type { AIAnalysis, WsEvent, WsIncidentOpen } from "@/types";

const markdownCell = (value: unknown) => String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");

export function generateReport(
  incident: WsIncidentOpen,
  events: WsEvent[],
  analysis: AIAnalysis | null
): string {
  const generatedAt = new Date().toISOString();
  const incidentId = incident.incident_id || "N/A";
  const eventRows = events.map((event, index) => `| ${index + 1} | ${markdownCell(event.type)} | ${markdownCell(JSON.stringify(event))} |`).join("\n");
  const aiAnalysis = analysis
    ? `${analysis.summary}\n\nMITRE Technique: ${analysis.mitre_technique}\nMITRE Tactic: ${analysis.mitre_tactic}\nRisk Score: ${analysis.risk_score}/100`
    : "AI triage was not run for this incident.";

  return `# INCIDENT FORENSIC REPORT
Generated: ${generatedAt}
Classification: CONFIDENTIAL

---

## Executive Summary
${incident.attack_type.replace(/_/g, " ")} activity with ${incident.severity} severity was detected from ${incident.source_ip} in ${incident.country}.

---

## Section 1  Incident Metadata

| Field | Value |
|---|---|
| Incident ID | ${markdownCell(incidentId)} |
| Source IP | ${markdownCell(incident.source_ip)} |
| Country | ${markdownCell(incident.country)} |
| ASN | ${markdownCell(incident.asn)} |
| Severity | ${markdownCell(incident.severity)} |
| Risk Score | ${incident.risk_score}/100 |
| MITRE Technique | ${markdownCell(incident.mitre_technique)} |
| MITRE Tactic | ${markdownCell(incident.mitre_tactic)} |
| TOR Exit Node | ${incident.is_tor ? "yes" : "no"} |
| VPN Detected | ${incident.is_vpn ? "yes" : "no"} |
| Timestamp | ${markdownCell(incident.timestamp)} |

---

## Section 2  Attack Timeline

| # | Event Type | Detail |
|---|---|---|
${eventRows}

---

## Section 3  AI Threat Analysis

${aiAnalysis}

---

## Section 4  Automated Defense Response

Action Taken: ${analysis?.action_taken ?? "N/A"}
Detail: ${analysis?.action_detail ?? "N/A"}

---

*Report generated by SOC AI Copilot v1.0*`;
}
